### ISSUE TITLE
Update for --new-pr?

### ISSUE THREAD

**Issue by verdurin** [rjeschmi/docker-easybuild-centos7#1]
Could this be refactored to use the native `--new-pr` feature in EB now?

**Comment by rjeschmi** [comment]
Yeah I'll look at it. Some of these sorts of things I've moved out into a
script that will call EB.

**Comment by rjeschmi** [comment]
I'm really really going to look at this now.

I'm going to try and just pass through to easybuild inside the container for now, so you could do what you want with that.

I'm also going to create a master container that can start up some other interesting tests perhaps.

**Comment by rjeschmi** [comment]
I'm not sure if this is still needed or not. I guess if you run a shell in easybuild-centos7:develop it might be interesting. It should be updated to the newest repos (but I often just map it to my local repos so there really isn't anything "in" the container)
